---
- name: Stat spec file on bootstrap node
  stat:
    path: "{{ item }}"
  register: stat_ceph_spec_files
  become: true
  loop:
    - "{{ ceph_spec }}"

- name: Fail if spec file is missing
  fail:
    msg: "{{ item.invocation.module_args.path }} does not exist"
  loop: "{{ stat_ceph_spec_files.results | list }}"
  when: not item.stat.exists

- name: Set ceph CLI
  set_fact:
    ceph_cli: |
      {{ container_cli }} run --rm {{ container_options }}
      --volume {{ ceph_config_home}}:/etc/ceph:z
      --volume {{ ceph_spec }}:{{ container_ceph_spec }}:z
      {{ ceph_container_ns }}/{{ ceph_container_image }}:{{ ceph_container_tag }}
      ceph --fsid {{ fsid }} -c {{ ceph_conf }} -k {{ admin_keyring }}

- name: Get the ceph orchestrator status
  command: "{{ ceph_cli }} orch status --format json"
  register: ceph_orch_status
  become: true

- name: Fail if ceph orchestrator is not available
  fail:
    msg: "'ceph orch status' returned {{ ceph_orch_status.stdout | from_json }}"
  when: 
    - not (ceph_orch_status.stdout | from_json).available

- name: Apply spec
  command: "{{ ceph_cli }} orch apply --in-file {{ container_ceph_spec }}"
  register: ceph_spec_apply_output
  become: true

- name: Show results of spec apply
  debug:
    msg: "{{ ceph_spec_apply_output }}"
  when: verbose
