---
# Minimal tasks to create the RBD key to get us moving
# Assumes the following module is in ANSIBLE_LIBRARY=/usr/share/ansible/library/
#   https://github.com/ceph/ceph-ansible/blob/master/library/ceph_key.py

- name: create keys data structure (from pools) if none was provided
  block:
    - name: Make secret key
      command: |
        python3 -c 'import os,struct,time,base64; key = os.urandom(16); header = struct.pack("<hiih", 1, int(time.time()), 0, len(key)) ; print(base64.b64encode(header + key).decode())'
      register: python_key_command
    - name: Define keys data structure
      set_fact:
        keys:
          - name: "{{ client_name }}"
            caps:
              mgr: "allow *"
              mon: "allow r"
              osd: "allow class-read object_prefix rbd_children, {{ allow_pool }}"
            key: "{{ secret_key }}"
            mode: "0600"
      vars:
        client_name: "client.openstack"
        secret_key: "{{ python_key_command.stdout }}"
        allow_pool: >-
          {% for pool in pools -%}
          allow rwx pool={{ pool }}{% if not loop.last %}, {% endif %}
          {%- endfor %}
  when:
    - keys is not defined

- name: create cephx key(s)
  ceph_key:
    import_key: true
    name: "{{ item.name }}"
    caps: "{{ item.caps }}"
    mode: "{{ item.mode }}"
    secret: "{{ item.key | default('') }}"
    cluster: "{{ cluster }}"
    dest: "{{ ceph_config_home }}"
    owner: "{{ ceph_uid  }}"
    group: "{{ ceph_uid  }}"
  environment:
    CEPH_CONTAINER_IMAGE: "{{ ceph_container_ns + '/' + ceph_container_image + ':' + ceph_container_tag }}"
    CEPH_CONTAINER_BINARY: "{{ container_cli }}"
  become: true
  loop: "{{ keys }}"
  when: keys | length > 0
