---
# Minimal idempotent tasks to create the RBD pools to get us moving

- name: Set ceph_cli
  include_tasks: ceph_cli.yaml

- name: Create pools
  command: "{{ ceph_cli }} osd pool create {{ item }}"
  loop: "{{ pools }}"
  register: pool_create
  become: true

- name: Show pool creation
  debug:
    msg: "{{ pool_create }}"
  when: verbose

- name: Label pools
  command: "{{ ceph_cli }} osd pool application enable {{ item }} rbd"
  loop: "{{ pools }}"
  register: pool_label
  become: true

- name: Show pool labeling
  debug:
    msg: "{{ pool_label }}"
  when: verbose
