---
- name: Stat cephadm file
  stat:
    path: "{{ cephadm_bin }}"
  register: stat_cephadm
  become: true
  ignore_errors: true

- name: Fail if cephadm is not available
  fail:
    msg: "{{ cephadm_bin }} does not exist"
  when: not stat_cephadm.stat.exists

- name: List Ceph daemon instances on this host
  shell: "{{ cephadm_bin }} ls --no-detail"
  register: cephadm_ls
  become: true

- name: Ensure fsid variable is set if none was provided
  block:
    - name: Set list of found FSIDs
      set_fact:
        fsids: "{{ cephadm_ls.stdout | from_json | json_query('[].fsid') | sort | unique }}"
    - name: Fail if >1 FSID was discovered
      fail:
        msg: |
          Multiple FSIDs were found. This Ansible role does not
          support management of multiple Ceph clusters on one host.
      when: fsids | length > 1
    - name: Set FSID to the discovered value
      set_fact:
        fsid: "{{ fsids[0] }}"
      when: fsids | length == 1
    - name: Set random fsid if no running ceph containers were found
      set_fact:
        fsid: "{{ 99999999 | random | to_uuid | lower }}"
      when: fsids | length == 0
  when: fsid is not defined or (fsid is defined and fsid | length == 0)

- name: Set first monitor IP
  set_fact:
    first_mon_ip: "{{ ( hostvars[bootstrap_host]['storage_ip'] |
                        default(hostvars[bootstrap_host]['ctlplane_ip']) )
                        | default(ansible_host) }}"

- name: Set admin_keyring and ceph_conf facts
  set_fact:
    admin_keyring: "{{ ceph_config_home }}/{{ cluster }}.client.admin.keyring"
    ceph_conf: "{{ ceph_config_home }}/{{ cluster }}.conf"

- name: Ensure /etc/ceph exists
  file:
    path: /etc/ceph
    state: directory
  become: true

- name: Ensure specs directory exists
  file:
    path: "/home/{{ ceph_ssh_user }}/specs"
    owner: "{{ ceph_ssh_user }}"
    group: "{{ ceph_ssh_user }}"
    mode: '0755'
    state: directory
  become: true

- name: Set ceph_spec facts
  set_fact:
    ceph_spec: "/home/{{ ceph_ssh_user }}/specs/ceph_spec.yaml"
    ceph_spec_ansible_host: "{{ role_path }}/files/ceph_spec.yaml"

- name: Stat spec file on ansible host
  stat:
    path: "{{ ceph_spec_ansible_host }}"
  register: stat_ceph_spec_file_on_ansible_host
  delegate_to: localhost
  become: true

- name: push ceph_spec to bootstrap node if spec file exsits
  copy:
    src: "{{ ceph_spec_ansible_host }}"
    dest: "{{ ceph_spec }}"
    owner: "{{ ceph_ssh_user }}"
    group: "{{ ceph_ssh_user }}"
    mode: '0644'
  become: true
  when: stat_ceph_spec_file_on_ansible_host.stat.exists
