---
- name: Genereate Ceph Spec file
  hosts: localhost
  vars:
    metal: "/home/stack/wallaby/standard/deployed-metal-oc0.yaml"
    spec: "/home/stack/wallaby/standard/ceph_spec.yaml"
    roles: "/home/stack/templates/roles_data.yaml"
    types:
      - mon
      - mgr
      - osd
  tasks:
    - name: Call ceph_spec_boostrap module
      ceph_spec_bootstrap:
        deployed_metalsmith: "{{ metal }}"
        #tripleo_roles: "{{ roles }}"
        #ceph_spec: "{{ spec }}"
        #ceph_service_types: "{{ types }}"
