---
- name: Genereate Ceph Spec file
  hosts: localhost
  vars:
    new_spec: "/home/stack/wallaby/standard/ceph_spec.yaml"
    metal: "/home/stack/wallaby/standard/deployed-metal-oc0.yaml"
    inv: "/home/stack/config-download/oc0/tripleo-ansible-inventory.yaml"
    roles: "/home/stack/templates/roles_data.yaml"
    #inv: "/home/stack/wallaby/dynamic_spec/inv/standalone_inventory.yml"
    # osd_spec:
    #   data_devices:
    #     paths:
    #       - /dev/ceph_vg/ceph_lv_data
  tasks:
    - name: Call ceph_spec_boostrap module
      ceph_spec_bootstrap:
        new_ceph_spec: "{{ new_spec }}"
        tripleo_ansible_inventory: "{{ inv }}"
        #deployed_metalsmith: "{{ metal }}"
        #tripleo_roles: "{{ roles }}"
        #osd_spec: "{{ osd_spec }}"
