---
- name: Deploy Ceph with cephadm
  hosts: mgrs[0]
  vars:
    bootstrap_host: "{{ groups['mgrs'][0] }}"
    spec_on_bootstrap: false
  tasks:
    # assumption:
    #   cd /usr/share/ansible/roles/
    #   ln -s /home/stack/wallaby/external/tripleo_cephadm
    - name: Satisfy Ceph prerequisites
      import_role:
        role: tripleo_cephadm
        tasks_from: pre

    - name: Bootstrap Ceph
      import_role:
        role: tripleo_cephadm
        tasks_from: bootstrap

    - name: Apply Ceph spec
      import_role:
        role: tripleo_cephadm
        tasks_from: apply_spec
      when: not spec_on_bootstrap
