---
- name: Deploy Ceph with cephadm
  hosts: mgrs[0]
  vars:
    bootstrap_host: "{{ groups['mgrs'][0] }}"
    ceph_ssh_user: ceph-admin
    cephadm_bin: /usr/sbin/cephadm
    cluster: ceph
    ceph_config_home: "/etc/ceph"
    spec_on_bootstrap: false # not recommended
    verbose: true
  tasks:
    - name: Satisfy prerequisites
      include_tasks: cephadm_aux/pre.yaml

    - name: Bootstrap Ceph
      include_tasks: cephadm_aux/bootstrap.yaml

    - name: Apply spec
      include_tasks: cephadm_aux/apply_spec.yaml
      when: not spec_on_bootstrap
