---
- hosts: allovercloud
  become: true
  gather_facts: false
  vars:
    pkgs:
      - git
      - emacs-nox
      - vim
      - tmux
      - https://download.ceph.com/rpm-pacific/el8/noarch/cephadm-16.2.0-0.el8.noarch.rpm
  tasks:
    - name: create base repo file
      copy:
        dest: "/etc/yum.repos.d/CentOS-BaseOS.repo"
        content: |
          [Base]
          name=baseos
          baseurl=http://mirror.centos.org/$contentdir/$releasever/BaseOS/$basearch/os/
          gpgcheck=0
          enabled=1
    
    - name: create appstream repo file
      copy:
        dest: "/etc/yum.repos.d/CentOS-AppStream.repo"
        content: |
          [AppStream]
          name=app-stream
          baseurl=http://mirror.centos.org/$contentdir/$releasever/AppStream/$basearch/os/
          gpgcheck=0
          enabled=1

    - name: create ceph repo file
      copy:
        dest: "/etc/yum.repos.d/ceph.repo"
        content: |
          [Ceph]
          name=Ceph $basearch
          baseurl=https://download.ceph.com/rpm-pacific/el8/$basearch
          gpgcheck=0
          enabled=1

    - name: install packages
      dnf:
        name: "{{ pkgs }}"
        state: latest
        disable_gpg_check: true